#!/bin/bash
DATE="2020-11-01"
TIME="16:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="17:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="18:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="19:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="20:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="21:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="22:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="23:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="24:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
DATE="2020-11-02"; TIME="00:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 
TIME="01:00"
./txtempus -v -n -s WWVB -t "$DATE $TIME" 